//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Getting = new HashSet<Getting>();
        }
    
        public int CodeBook { get; set; }
        public Nullable<int> codeAt { get; set; }
        public string Title { get; set; }
        public Nullable<int> SectionD { get; set; }
        public string YearPublish { get; set; }
        public Nullable<int> CountPage { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Getting> Getting { get; set; }
    }
}
