//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Getting
    {
        public int NumberGet { get; set; }
        public Nullable<System.DateTime> DateGetting { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public Nullable<int> NumberReader { get; set; }
        public Nullable<int> codeBooks { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
